name: Deploy to EC2 on Main Push

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        node-version: [16.x]

    steps:
    - name: Set up Node.js
      uses: actions/setup-node@v3
      with:
        node-version: ${{ matrix.node-version }}
    - name: Debugging Permissions
      run: |
        mkdir -p ~/.ssh
        ls -la /home/runner
        ls -la /home/runner/.ssh

    - name: Set Up SSH Key
      run: |
        echo "${{ secrets.SSH_PRIVATE_KEY }}" > ~/.ssh/id_rsa
        chmod 600 ~/.ssh/id_rsa
        ssh-keyscan -H  15.207.14.178 >> ~/.ssh/known_hosts

    - name: Deploy to EC2
      run: |
        rsync -avz  -e "ssh -o StrictHostKeyChecking=no" $GITHUB_WORKSPACE/ ubuntu@:15.207.14.178 /home/ubuntu/myweb.com/
